openapi: '3.0.2'
info:
  title: Entries API
  description: API for fetching entries in a ledger.
  license:
    name: LGPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: '0.0.0'
servers:
  - url: https://locahost:3333/

paths:
  /entries:
    get:
      summary: List entries
      description: List entries
      tags:
        - Entries
      parameters:
        - $ref: 'shared.yml#/components/parameters/cursor'
        - $ref: 'shared.yml#/components/parameters/limit'
      operationId: listEntries
      responses:
        '200':
          $ref: '#/components/responses/listEntries'

components:
  schemas:
    amount:
      type: object
      properties:
        value:
          type: string
          format: int64
        currency:
          type: string
          maxLength: 3
          minLength: 3
      required:
        - "value"
        - "currency"
    entry:
      type: object
      properties:
        id:
          $ref: 'shared.yml#/components/schemas/uuidv7'
        transactionID:
          $ref: 'shared.yml#/components/schemas/uuidv7'
        description:
          type: string
        debitAccount:
          $ref: 'shared.yml#/components/schemas/uuidv7'
        creditAccount:
          $ref: 'shared.yml#/components/schemas/uuidv7'
        amount:
          $ref: '#/components/schemas/amount'
        createdAt:
          $ref: 'shared.yml#/components/schemas/time'
  responses:
    listEntries:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              entries:
                type: array
                items:
                  $ref: '#/components/schemas/entry'
