openapi: '3.0.2'
info:
  title: GoLuca
  description: API for interacting with a simple ledger.
  license:
    name: LGPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: '0.0.0'
servers:
  - url: https://localhost:3333
tags:
  - name: Accounts
    description: 'Operations for interacting with account object. 
      An account is a pre-requisite for creating transactions, and maintains a derived running balance of an account.'
  - name: Transactions
    description: Operations for interacting with transaction object.
       A transaction holds the information of how money effects accounts.
       A transaction is made up of accounting/ledger entries. A single entry must be double-entry, and non composite.
paths:
# accounts
  /accounts:
    $ref: 'accounts.yml#/paths/~1accounts'
  /accounts/{accountId}:
    $ref: 'accounts.yml#/paths/~1accounts~1{accountId}'
# transactions
  /transaction:
    $ref: 'transactions.yml#/paths/~1transactions'
  /transactions/{transactionId}:
    $ref: 'transactions.yml#/paths/~1transactions~1{transactionId}'
