name: buf

on: pull_request
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: buf-setup-action
        uses: bufbuild/buf-setup-action@v1.6.0
        with:
          github_token: ${{ github.token }}
      - name: buf-lint-action
        uses: bufbuild/buf-lint-action@v1.0.1
        with:
          input: 'proto'
