name: buf

on: pull_request
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: buf-setup-action
        uses: bufbuild/buf-setup-action@v1.50.0
        with:
          github_token: ${{ github.token }}
      - name: buf-lint-action
        uses: bufbuild/buf-lint-action@v1.1.1
        with:
          input: 'proto'
      - name: buf-breaking
        uses: bufbuild/buf-breaking-action@v1.1.4
        with:
          input: 'proto'
          against: 'https://github.com/hampgoodwin/GoLuca.git#branch=main,ref=HEAD,subdir=proto'
