name: buf check
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Warm nix develop environment
        run: nix develop .#goluca -c echo "nix develop environment warmed"
      - name: buf lint, format, and breaking
        shell: nix develop .#goluca --command bash {0}
        run: |
          buf --version
          buf lint proto
          buf format proto -w
          buf breaking proto --against 'https://github.com/hampgoodwin/GoLuca.git#branch=main,ref=HEAD,subdir=proto'
          
