name: coverage
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Warm nix develop environment
        run: nix develop .#goluca -c echo "nix develop environment warmed"
      - name: containers up
        run: nix develop .#goluca -c make dbup && make natsup && docker container ls -a
      - name: test
        shell: nix develop .#goluca --command bash {0}
        run: |
          go version
          make test
      - name: containers down
        run: nix develop .#goluca -c make down

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
          flag-name: Go-1.24
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
