name: golangci-lint
on: [push]
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: nix flake check
        run: nix flake check
      - name: go version
        run: nix develop .#goluca -c go version
      - name: lint
        run: nix develop .#goluca -c golangci-lint version && nix develop .#goluca -c make lint
  
